ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.exploreops.online
CATALOGUE_HOST: catalogue-dev.exploreops.online
REDIS_HOST: redis-dev.exploreops.online
USER_HOST: user-dev.exploreops.online
CART_HOST: cart-dev.exploreops.online
MYSQL_HOST: mysql-dev.exploreops.online
SHIPPING_HOST: shipping-dev.exploreops.online
PAYMENT_HOST: payment-dev.exploreops.online
RABBITMQ_HOST: rabbitmq-dev.exploreops.online

